PerroAventurero/Controllers/AfiliacionesController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PerroAventurero.Models;
using MailKit;
using MimeKit;
using MailKit.Net.Smtp;

namespace PerroAventurero.Controllers
{
    public class AfiliacionesController : Controller
    {
        private readonly PAContext _context;

        public AfiliacionesController(PAContext context)
        {
            _context = context;
        }


        [Authorize(Roles = "Administrator")]
        // GET: Afiliaciones
        public async Task<IActionResult> Index()
        {
            var pAContext = _context.Afiliacions.Where(a => a.EsAceptada == null).Include(a => a.CedulaClienteNavigation).Include(a => a.CedulaNavigation);
            return View(await pAContext.ToListAsync());
        }

        [Authorize(Roles = "Administrator")]
        // GET: Afiliaciones/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var afiliacion = await _context.Afiliacions
                .Include(a => a.CedulaClienteNavigation)
                .Include(a => a.CedulaNavigation)
                .FirstOrDefaultAsync(m => m.Codigo == id);
            if (afiliacion == null)
            {
                return NotFound();
            }

            return View(afiliacion);
        }

        public async Task<IActionResult> Accept(int id)
        {

            var afiliacion = await _context.Afiliacions.FindAsync(id);

            Cliente cliente = await _context.Clientes.FindAsync(afiliacion.CedulaCliente);
            DateTime date = new DateTime(afiliacion.Fecha.Value.Year + 1, afiliacion.Fecha.Value.Month, afiliacion.Fecha.Value.Day, afiliacion.Fecha.Value.Hour, afiliacion.Fecha.Value.Minute, afiliacion.Fecha.Value.Second);

            string body = "Su afiliación al club Aventuras con Descuentos ha sido ACEPTADA.\n\n" +
                               "Su código de afiliación es: " + afiliacion.Codigo.ToString() + "\n"+
                               "Su afiliación comienza el día: " + afiliacion.Fecha.ToString() + "\n" +
                               "Su afiliación vence el día: " + date.ToString();

            sendStatus(body, cliente);

             afiliacion.EsAceptada = true;
            _context.Update(afiliacion);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Reject(int id)
        {

            var afiliacion = await _context.Afiliacions.FindAsync(id);
            Cliente cliente = await _context.Clientes.FindAsync(afiliacion.CedulaCliente);

            String body = "Lo sentimos, su afiliación fue rechazada. \n" +
                               "Encontramos algunos problemas con el comprobante de pago enviado.  \n" +
                               "Agradecemos el apoyo. \n" +
                               "Si desea realizar una nueva solicitud por favor vuelva a realizar el proceso de afiliación";

            sendStatus(body, cliente);

            _context.Afiliacions.Remove(afiliacion);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        private void sendStatus(string body, Cliente cliente) {

            MimeMessage message = new MimeMessage();
            message.From.Add(new MailboxAddress("Perro Aventurero", "perroaventurero.info@gmail.com"));
            SmtpClient client = new SmtpClient();
            string email = "perroaventurero.info@gmail.com";
            string password = "paonline08";

            message.To.Add(MailboxAddress.Parse(cliente.Correo.ToString()));
            message.Subject = "Estado de afiliacion a club Aventuras con Descuentos";
            message.Body = new TextPart("plain")
            {
                Text = body,
            };

            try
            {
                client.Connect("smtp.gmail.com", 465, true);
                client.Authenticate(email, password);
                client.Send(message);
            }
            catch (Exception ex)
            {

            }
            finally
            {

                client.Disconnect(true);
                client.Dispose();
            }

        }

        // GET: Afiliaciones/Create
        [Authorize(Roles = "Normal")]
        public IActionResult Create()
        {
            string CedulaCliente = null;
            CedulaCliente = User.Identity.Name;
            if (CedulaCliente != null)
            {

                ViewData["CedulaCliente"] = new SelectList(_context.UsuarioComuns, "CedulaCliente", "CedulaCliente");
                ViewData["Cedula"] = new SelectList(_context.UsuarioAdministradors, "Cedula", "Cedula");
                return View();
            }
            else {
                return Redirect("/Auth/Login");
            }

        }

        // POST: Afiliaciones/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormFile files)
        {

            var CedulaCliente = User.Identity.Name;
            if (_context.Afiliacions.Where(af => af.CedulaCliente == CedulaCliente).FirstOrDefault() == null)
            {
                if (files != null)
                {
                    Afiliacion afiliacionTemporal = new Afiliacion();

                    //Agregar codigo desde bd
                    //afiliacionTemporal.Codigo = 
                    afiliacionTemporal.CedulaCliente = CedulaCliente;
                    afiliacionTemporal.Fecha = DateTime.Today;
                    //afiliacionTemporal.ComprobantePago = 
                    if (files.Length > 0)
                    {
                        //Getting FileName
                        var fileName = Path.GetFileName(files.FileName);
                        //Getting file Extension
                        var fileExtension = Path.GetExtension(fileName);
                        // concatenating  FileName + FileExtension
                        var newFileName = String.Concat(Convert.ToString(Guid.NewGuid()), fileExtension);

                        using (var target = new MemoryStream())
                        {
                            files.CopyTo(target);
                            afiliacionTemporal.ComprobantePago = target.ToArray();
                        }

                        int code;


                        //Agregar codigo ramdon verificando los que hay en la bd
                        do
                        {
                            code = generateCode();
                        } while (_context.Afiliacions.Where(af => af.Codigo == code).FirstOrDefault() != null);

                        afiliacionTemporal.Codigo = code;
                        afiliacionTemporal.CedulaCliente = CedulaCliente;
                        afiliacionTemporal.Fecha = DateTime.Today;

                        _context.Add(afiliacionTemporal);
                        await _context.SaveChangesAsync();

                    }
                    ViewBag.r = "Se ha afiliado exitosamente";
                    return View();
                }
                else
                {
                    //Cuando no envia comprobante, ponerle mensajito de que tiene que ingresar comprobante y no dejarlo pasar.
                    //Ver a donde lo mando, solo puse eso para que dejara de molestar
                    ModelState.AddModelError("ComprobantePago", "Debe ingresar un comprobante de pago");
                    return View();
                }
                
            }
            else
            {
                //Ver a donde lo mando, solo puse eso para que dejara de molestar
                //Ya tiene una afiliacion a su nombre
                ModelState.AddModelError("ComprobantePago", "Ya tiene una afiliación a su nombre");
                return View();
            }
        }


        private int generateCode()
        {
            return new Random().Next(10000, 99999);
        }


        // GET: Afiliaciones/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var afiliacion = await _context.Afiliacions.FindAsync(id);
            if (afiliacion == null)
            {
                return NotFound();
            }
            ViewData["CedulaCliente"] = new SelectList(_context.UsuarioComuns, "CedulaCliente", "CedulaCliente", afiliacion.CedulaCliente);
            ViewData["Cedula"] = new SelectList(_context.UsuarioAdministradors, "Cedula", "Cedula", afiliacion.Cedula);
            return View(afiliacion);
        }

        // POST: Afiliaciones/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Codigo,CedulaCliente,Cedula,Fecha,ComprobantePago,EsAceptada")] Afiliacion afiliacion)
        {
            if (id != afiliacion.Codigo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(afiliacion);
                    await _context.SaveChangesAsync();

PerroAventurero/Views/Afiliaciones/Create.cshtml
@section Styles{
    <link rel="stylesheet" href="~/css/indexUser.css" />
}

@model PerroAventurero.Models.Afiliacion
@{
    ViewData["Title"] = "Create";
}

@*<h1>Create</h1>

    <h4>Afiliacion</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Codigo" class="control-label"></label>
                    <input asp-for="Codigo" class="form-control" />
                    <span asp-validation-for="Codigo" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CedulaCliente" class="control-label"></label>
                    <select asp-for="CedulaCliente" class="form-control" asp-items="ViewBag.CedulaCliente"></select>
                </div>
                <div class="form-group">
                    <label asp-for="Cedula" class="control-label"></label>
                    <select asp-for="Cedula" class="form-control" asp-items="ViewBag.Cedula"></select>
                </div>
                <div class="form-group">
                    <label asp-for="Fecha" class="control-label"></label>
                    <input asp-for="Fecha" class="form-control" />
                    <span asp-validation-for="Fecha" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ComprobantePago" class="control-label"></label>
                    <input asp-for="ComprobantePago" class="form-control" />
                    <span asp-validation-for="ComprobantePago" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EsAceptada" class="control-label"></label>
                    <input asp-for="EsAceptada" class="form-control" />
                    <span asp-validation-for="EsAceptada" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>*@






<div class="header">
    <div class="w-container">
        <h1 class="main-heading">perro aventurero</h1>
        <div class="divider"></div>
        <div class="main-subtitle">&quot;PERRO AVENTURERO...compartiendo  una vida de aventuras con nuestros mejores amigos!&quot;</div>
    </div>
</div>
<div class="row">
    <div class="col-6">
        <div id="aventurasContrato" class="about-section section">
            <h2 class="heading-2">Programa Aventuras con Descuentos</h2>
            <br />
            <h4 class="heading-2">Conoce nuestros términos y condiciones:</h4>
            <div class="divider grey"></div>
            <div class="row justify-content-center">
                <div class="container">
                    <p class="about-text">
                        Al realizar el envío del comprobante de pago usted acepta los términos y condiciones de nuestro programa. Una vez enviado debe
                        esperar para su correspondiente aceptación o, rechazo en caso de encontrar algún inconveniente. Nos estaremos comunicando por correo.
                        <br />
                        <br />
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-6">
        <div id="aventuras" class="section grey">
            <div id="aventuras" class="container">
                <h2 class="heading-14">Aventuras con descuento:</h2>
                <div class="divider grey"></div>
                <div class="row justify-content-center">
                    <form asp-action="Create" enctype="multipart/form-data">
                        <div class="form-row">
                            <div class="col">
                                <div class="form-control-file">
                                    <h5>Adjunte el comprobante de pago: </h5>
                                    <input name="files" type="file" accept="image/png, image/jpeg" onchange="loadFile(event)" />
                                    <img id="output" width="200" height="200" />
                                    <script>
                                        var loadFile = function (event) {
                                            var output = document.getElementById('output');
                                            output.src = URL.createObjectURL(event.target.files[0]);
                                            output.onload = function () {
                                                URL.revokeObjectURL(output.src) // free memory
                                            }
                                        };
                                    </script>
                                </div>
                                <span asp-validation-for="ComprobantePago" class="text-danger"></span>
                                @if (ViewBag.r != null)
                                {
                                    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
                                    <script type="text/javascript">
                                        $(document).ready(function () {
                                            alert('@ViewBag.r');
                                            window.location = "/Home/Index";
                                        });
                                    </script>
                                }
                            </div>
                            <div class="col">
                                <br />
                                <br />
                                <br />
                                <input type="submit" class="btn-lg btn-dark" value="Solicitar Afiliación">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

PerroAventurero/Views/Afiliaciones/Delete.cshtml
@model PerroAventurero.Models.Afiliacion

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Afiliacion</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ComprobantePago)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ComprobantePago)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EsAceptada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EsAceptada)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CedulaClienteNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CedulaClienteNavigation.CedulaCliente)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CedulaNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CedulaNavigation.Cedula)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Codigo" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PerroAventurero/Views/Afiliaciones/Details.cshtml
@model PerroAventurero.Models.Afiliacion

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Afiliacion</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ComprobantePago)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ComprobantePago)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EsAceptada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EsAceptada)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CedulaClienteNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CedulaClienteNavigation.CedulaCliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CedulaNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CedulaNavigation.Cedula)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Codigo">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PerroAventurero/Views/Afiliaciones/Edit.cshtml
@model PerroAventurero.Models.Afiliacion

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Afiliacion</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Codigo" />
            <div class="form-group">
                <label asp-for="CedulaCliente" class="control-label"></label>
                <select asp-for="CedulaCliente" class="form-control" asp-items="ViewBag.CedulaCliente"></select>
                <span asp-validation-for="CedulaCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cedula" class="control-label"></label>
                <select asp-for="Cedula" class="form-control" asp-items="ViewBag.Cedula"></select>
                <span asp-validation-for="Cedula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ComprobantePago" class="control-label"></label>
                <input asp-for="ComprobantePago" class="form-control" />
                <span asp-validation-for="ComprobantePago" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EsAceptada" class="control-label"></label>
                <input asp-for="EsAceptada" class="form-control" />
                <span asp-validation-for="EsAceptada" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PerroAventurero/Views/Afiliaciones/Index.cshtml
@model IEnumerable<PerroAventurero.Models.Afiliacion>

@section Styles{
    <link rel="stylesheet" href="~/css/indexUser.css" />
}

@{
    ViewData["Title"] = "Index";
}

<div class="header">
    <div class="w-container">
        <h1 class="main-heading">Afiliaciones</h1>
        <div class="divider"></div>

    </div>
</div>

<div id="eventos" class="section">
    <div class="container">
        <div class="row justify-content-center">
            @foreach (var item in Model)
            {

                <div class="col-3" style="padding: 10px; margin-bottom:10px;">
                    <div class="project-wrapper">
                        <a class="project-wrapper inline-block">
                            @if (item.ComprobantePago == null)
                            {
                                <img src="~/images/3.png" width="211" height="211" alt="">
                            }
                            else
                            {
                                <img src="@Url.Action("getImage", "Afiliaciones", new { id = item.Codigo })" width="200" height="300" alt="">
                            }
                            <div class="form-group">

                                <p class="paragraph">Cédula: @Html.DisplayFor(modelItem => item.CedulaCliente)</p>
                            </div>
                        </a>
                        <div class="row">
                            <div class="col-7">
                                <a nohref asp-action="Accept" asp-route-id="@item.Codigo" class="btn btn-dark" onClick="alert('Afiliación aceptada')">Aceptar</a>
                            </div>
                            <div class="col-4">
                                <a nohref  asp-action="Reject" asp-route-id="@item.Codigo" class="btn btn-dark" onClick="alert('Afiliación rechazada')">Rechazar</a>
                            </div>
                        </div>
                    </div>
                </div>

            }
        </div>

    </div>
</div>