PerroAventurero/Models/Evento.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace PerroAventurero.Models
{
    public partial class Evento
    {
        public Evento()
        {
            Reservas = new HashSet<Reserva>();
        }

        public int CodigoEvento { get; set; }
        public string Cedula { get; set; }
        
        [Required(ErrorMessage ="El nombre del evento es requerido")]
        [MaxLength(80)]
        public string NombreEvento { get; set; }


        [Required(ErrorMessage = "El lugar del evento es requerido")]
        [MaxLength(100)]
        public string Lugar { get; set; }


        [Required(ErrorMessage = "La dirección del evento es requerida")]
        [MaxLength(200)]
        public string Direccion { get; set; }


        [Required(ErrorMessage = "La fecha del evento es requerida")]
        [DataType(DataType.Date)]
        public DateTime Fecha { get; set; }


        [Required(ErrorMessage = "El precio de las entradas generales del evento es requerido")]
        [Range(1, int.MaxValue, ErrorMessage ="El precio de las entradas generales debe ser positivo")]
        public decimal PrecioGeneral { get; set; }

        [Required(ErrorMessage = "El precio de las entradas de niños del evento es requerido")]
        [Range(0, int.MaxValue, ErrorMessage = "El precio de las entradas de niños debe ser positivo")]
        public decimal PrecioNinno { get; set; }

        [Required(ErrorMessage = "La cantidad del aforo del evento es requerida")]
        [Range(1, int.MaxValue, ErrorMessage = "La cantidad de aforo debe ser un valor positivo")]
        public int CantidadAforo { get; set; }

        [Required(ErrorMessage = "La cantidad de grupos del evento es requerida")]
        [Range(1, int.MaxValue, ErrorMessage = "La cantidad de grupos debe ser un valor positivo")]
        public int CantidadGrupos { get; set; }

        [Required(ErrorMessage = "La hora de inicio de entrada al evento es requerida")]
        [DataType(DataType.Time)]
        public DateTime HoraInicio { get; set; }

        [Required(ErrorMessage = "La hora de final de entrada al evento es requerida")]
        [DataType(DataType.Time)]
        public DateTime HoraFinal { get; set; }

        public bool EnvioAnuncios { get; set; }
        public string Comentarios { get; set; }

        public byte[] Imagen { get; set; }

        public virtual UsuarioAdministrador CedulaNavigation { get; set; }
        public virtual ICollection<Reserva> Reservas { get; set; }
    }
}

PerroAventurero/Controllers/EventoesController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PerroAventurero.Models;
using MailKit;
using MimeKit;
using MailKit.Net.Smtp;


namespace PerroAventurero.Controllers
{
    public class EventoesController : Controller
    {
        private readonly PAContext _context;

        public EventoesController(PAContext context)
        {
            _context = context;
        }

        // GET: Eventoes
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Index(string searchString)
        {
            var pAContext = _context.Eventos.Where(e => e.Fecha > DateTime.Now).Include(e => e.CedulaNavigation);
            if (!String.IsNullOrEmpty(searchString))
            {
                pAContext = _context.Eventos.Where(e => e.NombreEvento.Contains(searchString) && e.Fecha > DateTime.Now).Include(e => e.CedulaNavigation);
            }
            return View(await pAContext.ToListAsync());
        }

        public async Task<IActionResult> SendReminders(int codigoEvento)
        {
            Reserva currentReservation;
            Evento evento = _context.Eventos.Where(e => e.CodigoEvento == codigoEvento).Include(e => e.CedulaNavigation).FirstOrDefault();
            Cliente cliente;
            List<Reserva> listOfReservations = new List<Reserva>();
            if (_context.Reservas.Where(r => r.CodigoEvento == codigoEvento && r.EsAceptada == true).FirstOrDefault() != null)
            {
                listOfReservations = await (_context.Reservas.Where(r => r.CodigoEvento == codigoEvento).Include(e => e.CedulaNavigation)).ToListAsync();
            }
            else
            {
                //No se tienen a quien mandar recordatorios, preguntar que se hace en estos casos, se tiene que terminar para que no de errores
                return RedirectToAction(nameof(Index));//hay que cambiarlo
            }



            MimeMessage message = new MimeMessage();
            message.From.Add(new MailboxAddress("Perro Aventurero", "perroaventurero.info@gmail.com"));
            SmtpClient client = new SmtpClient();
            string email = "perroaventurero.info@gmail.com";
            string password = "paonline08";

            message.Subject = "Recordatorio de evento Perro Aventurero";

         

            
            try
            {

                client.Connect("smtp.gmail.com", 465, true);
                client.Authenticate(email, password);

                do
                {
                    message.To.Clear();
                    currentReservation = listOfReservations.First();
                    cliente = _context.Clientes.Where(c => c.CedulaCliente == currentReservation.CedulaCliente).FirstOrDefault();

                    string body = "Perro aventurero le recuerda que el día " + evento.Fecha.ToString() + " se llevará a cabo el evento " + evento.NombreEvento +
                        " el cual tomará lugar en " + evento.Lugar + ". Poseemos una reservación con los siguientes datos: \n" +
                        "\nNombre de la persona: " + cliente.NombreCompleto + "\n" +
                        "Cédula: " + cliente.CedulaCliente + "\n" +
                        "Cantidad entradas generales: " + currentReservation.EntradasGenerales.ToString() + "\n" +
                        "Cantidad entradas niños: " + currentReservation.EntradasNinnos.ToString() + "\n" +
                        "Grupo : " + currentReservation.Grupo.ToString() + "\n" +
                        "Hora de entrada : " + currentReservation.HoraEntrada.ToString();

                    message.To.Add(MailboxAddress.Parse(cliente.Correo.ToString()));
                    //el mensaje que se env[ia
                    message.Body = new TextPart("plain")
                    {
                        Text = body,
                    };


                    client.Send(message);
                    listOfReservations.Remove(currentReservation);

                } while (listOfReservations.Count() >= 1);


               

            }
            catch (Exception ex)
            {


            }
            finally
            {

                client.Disconnect(true);
                client.Dispose();
            }


            //try
            //{

            //    SmtpClient client = new SmtpClient("smtp.gmail.com");
            //    client.Port = 587;
            //    client.EnableSsl = true;
            //    client.Timeout = 100000;
            //    client.EnableSsl = true;
            //    client.DeliveryMethod = SmtpDeliveryMethod.Network;
            //    client.UseDefaultCredentials = false;
            //    client.Credentials = new NetworkCredential("juanperez33op@gmail.com", "Juanitoperez33");
            //    MailMessage msg = new MailMessage();
            //    msg.From = new MailAddress("juanperez33op@gmail.com");
            //    msg.Subject = "Recordatorio de evento Perro Aventurero";

            //    do
            //    {
            //        msg.To.Clear();
            //        currentReservation = listOfReservations.First();
            //        cliente = _context.Clientes.Where(c => c.CedulaCliente == currentReservation.CedulaCliente).FirstOrDefault();

            //        msg.Body = "Perro aventurero le recuerda que el día " + evento.Fecha.ToString() + " se llevará a cabo el evento " + evento.NombreEvento +
            //            " el cual tomará lugar en " + evento.Lugar + ". Poseemos una reservación con los siguientes datos: \n" +
            //            "\nNombre de la persona: " + cliente.NombreCompleto + "\n" +
            //            "Cédula: " + cliente.CedulaCliente + "\n" +
            //            "Cantidad entradas generales: " + currentReservation.EntradasGenerales.ToString() + "\n" +
            //            "Cantidad entradas niños: " + currentReservation.EntradasNinnos.ToString() + "\n" +
            //            "Grupo : " + currentReservation.Grupo.ToString() + "\n" +
            //            "Hora de entrada : " + currentReservation.HoraEntrada.ToString();

            //        msg.To.Add(cliente.Correo.ToString());
            //        //Attachment data = new Attachment(textBox3.Text);
            //        //msg.Attachments.Add(data);
            //        client.Send(msg);//Aquí está el problema

            //        listOfReservations.Remove(currentReservation);

            //    } while (listOfReservations.Count() >= 1);
            //}
            //catch (Exception ex)
            //{
            //    // TODO: handle exception
            //    throw new InvalidOperationException(ex.Message);
            //}






            return RedirectToAction(nameof(Index));//hay que cambiarlo
        }

        // GET: Eventoes/Details/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evento = await _context.Eventos
                .Include(e => e.CedulaNavigation)
                .FirstOrDefaultAsync(m => m.CodigoEvento == id);
            ViewBag.Image = ViewImage(evento.Imagen);
            if (evento == null)
            {
                return NotFound();
            }

            return View(evento);
        }

        private string ViewImage(byte[] arrayImage)

        {
            string base64String = Convert.ToBase64String(arrayImage, 0, arrayImage.Length);
            return "data:image/png;base64," + base64String;
        }

        // GET: Eventoes/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            ViewData["Cedula"] = new SelectList(_context.UsuarioAdministradors, "Cedula", "Cedula");
            return View();
        }

        // POST: Eventoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CodigoEvento,Cedula,NombreEvento,Lugar,Direccion,Fecha,PrecioGeneral,PrecioNinno,CantidadAforo,CantidadGrupos,HoraInicio,HoraFinal,EnvioAnuncios,Comentarios")] Evento evento, IFormFile files)
        {

            if (ModelState.IsValid)
            {
                if (DateTime.Compare(DateTime.Now, evento.Fecha) > 0 || DateTime.Compare(DateTime.Now, evento.Fecha) == 0)
                {
                    ModelState.AddModelError("Fecha", "La fecha del evento debe ser porterior a la  fecha de hoy");
                    return View(evento);
                }

                evento.HoraInicio = new DateTime(evento.Fecha.Year, evento.Fecha.Month, evento.Fecha.Day, evento.HoraInicio.Hour, evento.HoraInicio.Minute, evento.HoraInicio.Second);
                evento.HoraFinal = new DateTime(evento.Fecha.Year, evento.Fecha.Month, evento.Fecha.Day, evento.HoraFinal.Hour, evento.HoraFinal.Minute, evento.HoraFinal.Second);


                if (DateTime.Compare(evento.HoraInicio,evento.HoraFinal) > 0 || DateTime.Compare(evento.HoraInicio, evento.HoraFinal) == 0)
                {
                    //Validar que la fecha hora final sea posterior que hora inicio, ver que hago cuando es mayor
                    ModelState.AddModelError("HoraFinal", "Hora final debe ser posterior a hora inicial");
                    return View(evento);
                }
                else
                {
                    if (files != null)
                    {
                        if (files.Length > 0)

PerroAventurero/Views/Shared/_Evento.cshtml
@model PerroAventurero.Models.Evento
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-4">
            Nombre
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.NombreEvento)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.Lugar)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.Lugar)
        </dd>
        <dt class="col-sm-4">
            Dirección
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class="col-sm-4">
            Precio general
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.PrecioGeneral)
        </dd>
        <dt class="col-sm-4">
            Precio niño
        </dt>
        <dd class="col-sm-6">
            @Html.DisplayFor(model => model.PrecioNinno)
        </dd>
    </dl>
</div>

@*<div class="container py-1">
    <div class="row">
        <div class="row">
            <div class="col-3">
                <h5>Nombre</h5>
            </div>
            <div class="col-3">
                @Html.DisplayFor(model => model.NombreEvento)
                <br>
            </div>
        </div>
        <div class="row">
            <div class="col-3">
                <h5>@Html.DisplayNameFor(model => model.Lugar)</h5>
            </div>
            <div class="col-3">
                @Html.DisplayFor(model => model.Lugar)
                <br><br />
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-3">
                <h5>Dirección</h5>
            </div>
            <div class="col-3">
                @Html.DisplayFor(model => model.Direccion)
                <br />
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-3">
                <h5>@Html.DisplayNameFor(model => model.Fecha)</h5>
            </div>
            <div class="col-3">
                @Html.DisplayFor(model => model.Fecha)
                <br />
                <br />
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-3">
                <h5>Precio general</h5>
            </div>
            <div class="col-3">
                @Html.DisplayFor(model => model.PrecioGeneral)
                <br />
                <br />
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-3">
                <h5>Precio niño</h5>
            </div>
            <div class="col-3">
                @Html.DisplayFor(model => model.PrecioNinno)
                <br />
                <br />
            </div>
        </div>
    </div>
</div>*@

PerroAventurero/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PerroAventurero</title>
    @RenderSection("Styles", false)
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/navUser.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/logo.png" width="85" sizes="(max-width: 479px) 50px, (max-width: 767px) 11vw, 85px" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Eventoes" asp-action="Index">Eventos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EmpresasAfiliadas" asp-action="Index">Empresas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Afiliaciones" asp-action="Index">Aventuras con Descuento</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reservas" asp-action="Index">Reservaciones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reportes" asp-action="Index">Reportes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="">
            @RenderBody()
    </main>

    <footer id="footer" class="section-f footer">
        <div class="container-f">
            <img src="~/images/2.jpg" width="235" sizes="(max-width: 479px)" />
            <p class="footer-text">2021 - Perro Aventurero</p>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PerroAventurero/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PerroAventurero</title>
    @RenderSection("Styles", false)
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/navUser.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/logo.png" width="85" sizes="(max-width: 479px) 50px, (max-width: 767px) 11vw, 85px"/></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (ViewData["Nav"] == "true")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" href="#eventos">Eventos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" href="#aventuras">Aventuras con descuento</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Eventos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Aventuras con descuento</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="">
        @RenderBody()
    </main>

    <footer id="footer" class="section-f footer">
        <div class="container-f">
            <img src="~/images/2.jpg" width="235" sizes="(max-width: 479px)" />
            <p class="footer-text">2021 - Perro Aventurero</p>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>