PerroAventurero/Models/EmpresasAfiliada.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace PerroAventurero.Models
{
    public partial class EmpresasAfiliada
    {
        public int CodigoEmpresa { get; set; }
        public string Cedula { get; set; }
        [Required(ErrorMessage = "El nombre de la empresa es requerido")]
        [StringLength(60, MinimumLength = 3)]
        [Display(Name = "Nombre de empresa")]
        public string NombreEmpresa { get; set; }
        [Required(ErrorMessage = "El correo de la empresa es requerido")]
        [RegularExpression(@"^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$", ErrorMessage = "El correo no corresponde a uno válido")]
        public string Correo { get; set; }
        public byte[] Logo { get; set; }
        [Required(ErrorMessage = "La categoría es requerida")]
        public string Categoria { get; set; }

        [Display(Name = "Télefono")]
        [Required(ErrorMessage = "Su télefono requerido")]
        public int? Telefono { get; set; }

        public string NombreContacto { get; set; }

        public virtual UsuarioAdministrador CedulaNavigation { get; set; }
    }
}

PerroAventurero/Controllers/EmpresasAfiliadasController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PerroAventurero.Models;
using System.Drawing;
using System.Drawing.Imaging;

namespace PerroAventurero.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class EmpresasAfiliadasController : Controller
    {
        private readonly PAContext _context;

        public EmpresasAfiliadasController(PAContext context)
        {
            _context = context;
        }

      

        [Authorize(Roles = "Administrator")]
        // GET: EmpresasAfiliadas
        public async Task<IActionResult> Index(string searchString)
        {
            var pAContext = _context.EmpresasAfiliadas.Include(e => e.CedulaNavigation);
            if (!String.IsNullOrEmpty(searchString))
            {
                pAContext = _context.EmpresasAfiliadas.Where(e => e.NombreEmpresa.Contains(searchString) || e.NombreContacto.Contains(searchString)).Include(e => e.CedulaNavigation);
            }
            List<byte[]> listP = new List<byte[]>();

            foreach (var empr in pAContext.ToList())
            {
                listP.Add(empr.Logo);
              
            }

            List<String> listt = ViewImage2(listP);

           ViewBag.List = listt;
           


            return View(await pAContext.ToListAsync());
        }

        private string ViewImage(byte[] arrayImage)

        {

            string base64String = Convert.ToBase64String(arrayImage, 0, arrayImage.Length);

            return "data:image/png;base64," + base64String;

        }

        private List<String> ViewImage2(List<byte[]> arrayImage)

        {
            List<String> listas = new List<String>();
            string base64String;
            foreach (var a in arrayImage)
            {
               base64String = "data:image/png;base64," + Convert.ToBase64String(a, 0, a.Length);
                listas.Add(base64String);
            }



            return listas;

        }


        // GET: EmpresasAfiliadas/Details/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empresasAfiliada = await _context.EmpresasAfiliadas
                .Include(e => e.CedulaNavigation)
                .FirstOrDefaultAsync(m => m.CodigoEmpresa == id);
            ViewBag.Image = ViewImage(empresasAfiliada.Logo);
            if (empresasAfiliada == null)
            {
                return NotFound();
            }

            return View(empresasAfiliada);
        }

        // GET: EmpresasAfiliadas/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            ViewData["Cedula"] = new SelectList(_context.UsuarioAdministradors, "Cedula", "Cedula");
            return View();
        }

        // POST: EmpresasAfiliadas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CodigoEmpresa,Cedula,NombreEmpresa,Correo,Logo,Categoria,Telefono,NombreContacto")] EmpresasAfiliada empresasAfiliada, IFormFile files)
        {
            if (ModelState.IsValid)
            {
                if (files != null)
                {
                    if (files.Length > 0)
                    {
                        //Getting FileName
                        var fileName = Path.GetFileName(files.FileName);
                        //Getting file Extension
                        var fileExtension = Path.GetExtension(fileName);
                        // concatenating  FileName + FileExtension
                        var newFileName = String.Concat(Convert.ToString(Guid.NewGuid()), fileExtension);

                        using (var target = new MemoryStream())
                        {
                            files.CopyTo(target);

                            empresasAfiliada.Logo = target.ToArray();
                        }



                        // ViewBag.Image = ViewImage(objfiles.ComprobantePago);

                    }
                }
                //empresasAfiliada.Cedula = session;
                _context.Add(empresasAfiliada);
                await _context.SaveChangesAsync();
                Boolean saved = EmpresasAfiliadaExists(empresasAfiliada.CodigoEmpresa);
                if (saved == true) {
                    ViewBag.r = "Empresa creada exitosamente";
                }
                else
                {

                    ViewBag.r = "Error, no se pudo crear la empresa";
                }

                //return RedirectToAction(nameof(Index));
            }

            ViewData["Cedula"] = new SelectList(_context.UsuarioAdministradors, "Cedula", "Cedula", empresasAfiliada.Cedula);
            //ViewData["Categoria"] = new SelectList(_context.EmpresasAfiliadas, "Categoria", "Categoria", empresasAfiliada.Categoria);
            return View(empresasAfiliada);
        }

        // GET: EmpresasAfiliadas/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empresasAfiliada = await _context.EmpresasAfiliadas.FindAsync(id);
            if (empresasAfiliada == null)
            {
                return NotFound();
            }
            ViewBag.Image = ViewImage(empresasAfiliada.Logo);
            
            ViewData["Cedula"] = new SelectList(_context.UsuarioAdministradors, "Cedula", "Cedula", empresasAfiliada.Cedula);
            return View(empresasAfiliada);
        }

        // POST: EmpresasAfiliadas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CodigoEmpresa,Cedula,NombreEmpresa,Correo,Logo,Categoria,Telefono,NombreContacto")] EmpresasAfiliada empresasAfiliada, IFormFile files)
        {
            if (id != empresasAfiliada.CodigoEmpresa)
            {
                return NotFound();
            }

            var empresasAfiliadaVieja = _context.EmpresasAfiliadas.Find(id);
            byte[] logoEmp = ViewBag.Image = empresasAfiliadaVieja.Logo;
            _context.Entry(empresasAfiliadaVieja).State = EntityState.Detached;

            if (ModelState.IsValid)
            {


                try
                {
                    if (files != null)
                    {
                        if (files.Length > 0)
                        {
                            //Getting FileName
                            var fileName = Path.GetFileName(files.FileName);
                            //Getting file Extension
                            var fileExtension = Path.GetExtension(fileName);
                            // concatenating  FileName + FileExtension
                            var newFileName = String.Concat(Convert.ToString(Guid.NewGuid()), fileExtension);

                            using (var target = new MemoryStream())
                            {
                                files.CopyTo(target);

                                empresasAfiliada.Logo = target.ToArray();
                            }

                        }
                        else
                        {
                            empresasAfiliada.Logo = logoEmp;
                        }
                    }
                    else
                    {
                        empresasAfiliada.Logo = logoEmp;
                    }
                    _context.Update(empresasAfiliada);
                    await _context.SaveChangesAsync();
                    Boolean right = EmpresasAfiliadaExists(empresasAfiliada.CodigoEmpresa);
                    if (right == true)
                    {
                        ViewBag.r = "Empresa modificada exitosamente";
                    }
                    else {
                        ViewBag.r = "Error, no se pudo moficar la empresa";
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmpresasAfiliadaExists(empresasAfiliada.CodigoEmpresa))
                    {
                        ViewBag.r = "Error, no se pudo moficar la empresa";
                    }
                    else
                    {
                        throw;
                    }
                }
                //return RedirectToAction(nameof(Index));
            }
            ViewData["Cedula"] = new SelectList(_context.UsuarioAdministradors, "Cedula", "Cedula", empresasAfiliada.Cedula);
            return View(empresasAfiliada);
        }

        // GET: EmpresasAfiliadas/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var empresasAfiliada = await _context.EmpresasAfiliadas
                .Include(e => e.CedulaNavigation)
                .FirstOrDefaultAsync(m => m.CodigoEmpresa == id);
            if (empresasAfiliada == null)
            {
                return NotFound();
            }

            return View(empresasAfiliada);
        }

        // POST: EmpresasAfiliadas/Delete/5
        [HttpPost, ActionName("Delete")]

PerroAventurero/Views/EmpresasAfiliadas/Create.cshtml
@model PerroAventurero.Models.EmpresasAfiliada

@section Styles{
    <link rel="stylesheet" href="~/css/indexUser.css" />
}

@{
    ViewData["Title"] = "Create";
}


<div class="header-empresa">
    <div class="container">
        <h1 class="main-heading">Empresas Afiliadas</h1>
        <div class="divider"></div>
    </div>
</div>

<div class="pt-2 row justify-content-md-center">
    <h4>Formulario de ingreso de empresa:</h4>
    <br />
</div>


<div class="container py-5">
    <form asp-action="Create" enctype="multipart/form-data">
        <div class="controls">
            <div class="row">
                <div class="col-sm-4">
                    <div class="form-group">
                        <label>Nombre de empresa:</label>
                        <input asp-for="NombreEmpresa" class="form-control" />
                        <span asp-validation-for="NombreEmpresa" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label>Categoría de empresa:</label>
                        <select asp-for="Categoria" class="form-control">
                            @*hacer que lo agarre de la bd*@
                            <option value="1">Servicio</option>
                            <option value="2">Producto</option>
                        </select>
                        @*<select asp-for="Categoria" class="form-control" asp-items="ViewBag.Categoria"></select>*@
                        <span asp-validation-for="Categoria" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-sm-4">
                    @*<label>Contacto de empresa:</label>*@

                    <div class="form-group">
                        <label>Teléfono:</label>
                        <input asp-for="Telefono" class="form-control" />
                        <span asp-validation-for="Telefono" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label>Correo electrónico:</label>
                        <input asp-for="Correo" class="form-control" type="email" />
                        <span asp-validation-for="Correo" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label>Nombre de contacto:</label>
                        <input asp-for="NombreContacto" class="form-control" />
                        <span asp-validation-for="NombreContacto" class="text-danger"></span>
                    </div>

                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label>Logo de empresa:</label>
                        <br />
                        <img id="output" width="200" height="200" src="@ViewBag.Image" />
                        <br />
                        <br />
                        <input name="files" type="file" accept="image/png, image/jpeg" onchange="loadFile(event)" required />
                        <span asp-validation-for="Logo" class="text-danger"></span>
                        <br />
                        <br />


                        <input type="submit" class="btn btn-dark" value="Guardar">

                        @if (ViewBag.r != null)
                        {
                            <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
                            <script type="text/javascript">
                        $(document).ready(function () {
                            alert("@ViewBag.r");
                            window.location = "/EmpresasAfiliadas/Index";
                    });
                            </script>
                        }
                        <script>
                            var loadFile = function (event) {
                                var output = document.getElementById('output');
                                output.src = URL.createObjectURL(event.target.files[0]);
                                output.onload = function () {
                                    URL.revokeObjectURL(output.src) // free memory
                                }
                            };
                        </script>

                    </div>
                </div>
            </div>

        </div>
      
    </form>
</div>




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PerroAventurero/Views/EmpresasAfiliadas/Delete.cshtml
@model PerroAventurero.Models.EmpresasAfiliada

@{
    ViewData["Title"] = "Delete";
}

<h1>Eliminar</h1>

<h3>Está seguro que desea eliminar esta empresa?</h3>
<div>
    <h4>Empresa</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreEmpresa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreEmpresa)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Correo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Correo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Logo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Logo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Categoria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Categoria)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CedulaNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CedulaNavigation.Cedula)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CodigoEmpresa" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PerroAventurero/Views/EmpresasAfiliadas/Edit.cshtml
@model PerroAventurero.Models.EmpresasAfiliada

@section Styles{
    <link rel="stylesheet" href="~/css/indexUser.css" />
}

@{
    ViewData["Title"] = "Edit";
}

<div class="header-empresa">
    <div class="container">
        <h1 class="main-heading">Empresas Afiliadas</h1>
        <div class="divider"></div>
    </div>
</div>

<div class="pt-2 row justify-content-md-center">
    <h4>Empresa:</h4>
    <br />
</div>

<!--<div class="m-0 row justify-content-md-center">
    <form asp-action="Edit" enctype="multipart/form-data">
        <input type="hidden" asp-for="CodigoEmpresa" />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>-->
@*<div class="form-group">
        <label asp-for="Cedula" class="control-label"></label>
        <select asp-for="Cedula" class ="form-control" asp-items="ViewBag.Cedula"></select>
    </div>*@


<!--<div class="form-control-file">
    <label>Logo de empresa:</label>
    <input name="files" type="file" accept="image/png, image/jpeg" onchange="loadFile(event)" />
    <img id="output" width="200" height="200" src="@ViewBag.Image" />
    <script>
        var loadFile = function (event) {
            var output = document.getElementById('output');
            output.src = URL.createObjectURL(event.target.files[0]);
            output.onload = function () {
                URL.revokeObjectURL(output.src) // free memory
            }
        };
    </script>
    <span asp-validation-for="Logo" class="text-danger"></span>
</div>
<hr />
<div class="form-group">
    <label>Nombre de empresa:</label>
    <input asp-for="NombreEmpresa" class="form-control" />
    <span asp-validation-for="NombreEmpresa" class="text-danger"></span>
</div>
<div class="form-group">
    <label>Categoría de empresa:</label>
    <input asp-for="Categoria" class="form-control" />-->
@*<select asp-for="Categoria" class="form-control" asp-items="ViewBag.Categoria"></select>*@
<!--<span asp-validation-for="Categoria" class="text-danger"></span>
</div>
<div>
    <label>Contacto de empresa:</label>-->
@*Si dice contactos, deberiamos dejar que la persona agregue varios telefonos a las empresas?*@
<!--<div class="form-row">
        <div class="form-group col-md-6">
            <label>Teléfono:</label>
            <input asp-for="Telefono" class="form-control" />
            <span asp-validation-for="Telefono" class="text-danger"></span>
        </div>

        <div class="form-group col-md-6">
            <label>Correo electrónico:</label>
            <input asp-for="Correo" class="form-control" type="email" />
            <span asp-validation-for="Correo" class="text-danger"></span>
        </div>

    </div>
</div>-->
@*<div class="form-group">
        <label asp-for="Logo" class="control-label"></label>
        <input asp-for="Logo" class="form-control" />
        <span asp-validation-for="Logo" class="text-danger"></span>
    </div>*@







<div class="container py-5">
    <form asp-action="Edit" enctype="multipart/form-data" method="post">

        <div class="row">
            <div class="col-sm-4">
                <div class="form-group">
                    <input type="hidden" asp-for="CodigoEmpresa" />
                    <label>Nombre de empresa:</label>
                    <input asp-for="NombreEmpresa" class="form-control" />
                    <span asp-validation-for="NombreEmpresa" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label>Categoría de empresa:</label>
                    <!--<select asp-for="Categoria" class="form-control">-->
                        @*hacer que lo agarre de la bd*@
                        @*@if (ViewBag.Category == "2")
            {
                <option value="1">Servicio</option>
                <option value="2" selected>Producto</option>
                }
            else
            {

                <option value="1" selected>Servicio</option>
                <option value="2">Producto</option>

            }*@

                        <!--<option value="1">Servicio</option>
                        <option value="2" selected>Producto</option>
                    </select>-->

                    @if (Model.Categoria == "2")
                    {
                        <select asp-for="Categoria" class="form-control">
                            <option value="1">Servicio</option>
                            <option value="2" selected>Producto</option>
                        </select>
                    }
                    else
                    {
                        <select asp-for="Categoria" class="form-control">
                            <option value="1" selected>Servicio</option>
                            <option value="2">Producto</option>
                        </select>
                    }

                    @*<select asp-for="Categoria" class="form-control" asp-items="ViewBag.Categoria"></select>*@
                    <span asp-validation-for="Categoria" class="text-danger"></span>
                </div>
            </div>
            <div class="col-sm-4">
                @*<label>Contacto de empresa:</label>*@

                <div class="form-group">
                    <label>Teléfono:</label>
                    <input asp-for="Telefono" class="form-control" />
                    <span asp-validation-for="Telefono" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label>Correo electrónico:</label>
                    <input asp-for="Correo" class="form-control" type="email" />
                    <span asp-validation-for="Correo" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label>Nombre de contacto:</label>
                    <input asp-for="NombreContacto" class="form-control" />
                    <span asp-validation-for="NombreContacto" class="text-danger"></span>
                </div>

            </div>
            <div class="col-sm-4">
                <div class="form-group">
                    <label>Logo de empresa:</label>
                    <br />
                    <img id="output" width="200" height="200" src="@ViewBag.Image" />
                    <br />
                    <br />
                    <input name="files" type="file" accept="image/png, image/jpeg" onchange="loadFile(event)" />
                    <span asp-validation-for="Logo" class="text-danger"></span>
                    <br />
                    <br />


                    <script>
                        var loadFile = function (event) {
                            var output = document.getElementById('output');
                            output.src = URL.createObjectURL(event.target.files[0]);
                            output.onload = function () {
                                URL.revokeObjectURL(output.src) // free memory
                            }
                        };
                    </script>

                </div>
                <div class="form-group">
                    <div class="row justify-content-right">
                        <div class="col-6 justify-content-center">
                            <input type="submit" value="Guardar" class="btn btn-dark" />
                            @if (ViewBag.r != null)
                            {
                                <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
                                <script type="text/javascript">
                        $(document).ready(function () {
                            alert("@ViewBag.r");
                            window.location = "/EmpresasAfiliadas/Index";
                    });
                                </script>
                            }

                        </div>

                        <div class="col-6 justify-content-center">

                        </div>
                    </div>

                </div>

            </div>
        </div>



    </form>
    <div @*class="deletebtn"*@>
        <form asp-action="Delete" asp-route-id="CodigoEmpresa" method="post">
            <input type="hidden" asp-for="CodigoEmpresa" />
            <input class="btn badge-dark" type="submit" onclick="return confirm('¿Está seguro que desea eliminar la empresa?')" value="Eliminar" />
        </form>
    </div>
    @*@using (Html.BeginForm("Delete", "EmpresasAfiliadas", FormMethod.Post))
        {

            <input type="submit" value="Eliminar" class="button-empresa" onclick="return confirm('¿Está seguro que desea eliminar esta empresa')" />
        }*@
</div>



@section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

PerroAventurero/Views/EmpresasAfiliadas/Index.cshtml
@model IEnumerable<PerroAventurero.Models.EmpresasAfiliada>

@section Styles{
    <link rel="stylesheet" href="~/css/company.css" />
}

@{ ViewData["Title"] = "Empresas"; }



<div class="header">
    <div class="container">
        <h1 class="main-heading">Empresas Afiliadas</h1>
        <div class="divider"></div>
        
    </div>
</div>

<div class="section-event container">
    <div class="container">
        <div class="row">
            <div class="col-10">
                <h1>Lista de empresas:</h1>
            </div>
            <div class="col-2 justify-content-right">
                <a asp-action="Create"><h5>+Nueva Empresa</h5></a>
            </div>
        </div>
    </div>
    <div class="container p-2">
        @using (Html.BeginForm())
        {
            <p>
                Buscar Empresa: @Html.TextBox("SearchString")
                <input type="submit" class="btn btn-dark" value="Buscar" />
            </p>
        }
    </div>  
    <div class="row justify-content-center">
        @foreach (var item in Model)
        {
            <div class="empresa-section col-sm-3">
                <div class="container justify-content-center">
                    <h4 class="name"><a class="nameLink" asp-action="Edit" asp-route-id="@item.CodigoEmpresa">@Html.DisplayFor(modelItem => item.NombreEmpresa)</a></h4>
                    <img class="imgLogo" width="200" height="200" src="@Url.Action("getImage", "EmpresasAfiliadas", new { id = item.CodigoEmpresa })" />
                    @*<div class="row justify-content-center">
                            <div class="col-6 justify-content-center">
                                <a class="button-empresa" >Detalles</a>
                            </div>

                            <div class="col-6 justify-content-center">
                                <form asp-action="Delete" asp-route-id="@item.CodigoEmpresa" method="post">
                                    <input class="button-empresa" type="submit" onclick="return confirm('¿Está seguro que desea eliminar la empresa:  @item.NombreEmpresa')" value="Eliminar" />
                                </form>
                            </div>
                        </div>*@
                </div>
            </div>
        }
    </div>
</div>


<style>
    .button {
        background-color: #4CAF50; /* Green */
        border: none;
        color: white;
        padding: 15px 32px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
    }



    .button4 {
        border-radius: 12px;
    }
</style>
<div>

    <fieldset>
        <div class="container">
            <div class="row">
                <div class="col-xs-12">


                    <div class="modal fade" tabindex="-1" id="modalDelete"
                         data-keyboard="false" data-backdrop="static">
                        <div class="modal-dialog modal-lg">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">¿Está seguro que desea eliminar la empresa seleccionada?</h5>
                                    @*<button type="button" class="close" data-dismiss="modal">
                                            ×
                                        </button>*@

                                </div>
                                <div class="modal-body">

                                </div>
                                <div class="modal-footer">
                                    <form asp-action="Delete">

                                       
                                        <input type="submit" value="Delete" class="btn btn-danger" />
                                    </form>
                                    <button type="button" id="btnHideModal" class="btn btn-primary button button4">
                                        Cancelar
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </fieldset>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js">
</script>
<script src="bootstrap/js/bootstrap.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $("#btnShowModal").click(function () {
            $("#modalDelete").modal('show');
        });

        $("#btnHideModal").click(function () {
            $("#modalDelete").modal('hide');
        });
    });
</script>

@*<button id="btnShowModal" type="button"
            class="btn btn-sm btn-default pull-left col-lg-11 button button4">
        Eliminar
    </button>*@