PerroAventurero/Models/Reserva.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace PerroAventurero.Models
{
    public partial class Reserva
    {
        public int CodigoReserva { get; set; }
        public int CodigoEvento { get; set; }
        public string CedulaCliente { get; set; }


        public string Cedula { get; set; }

        [Display(Name = "Entradas generales")]
        [Required(ErrorMessage = "Debe seleccionar la cantidad de entradas")]
        [Range(1, 100, ErrorMessage = "Debe ingresar un número válido")]
        public short EntradasGenerales { get; set; }

        [Display(Name = "Entradas niños")]
        [Range(0, 100, ErrorMessage = "Debe ingresar un número válido")]
        public short? EntradasNinnos { get; set; }


        public DateTime FechaReserva { get; set; }


        [Required(ErrorMessage = "Debe ingresar un grupo")]
        public short Grupo { get; set; }


        [Display(Name = "Hora de entrada")]
        [Required(ErrorMessage = "Debe seleccionar una hora de entraga")]
        [DataType(DataType.Time)]
        public DateTime HoraEntrada { get; set; }

        public bool? EsAceptada { get; set; }
        public byte[] ComprobantePago { get; set; }

        [Display(Name = "Precio total")]
        public decimal PrecioTotal { get; set; }
        public bool? Asistencia { get; set; }

        public virtual Cliente CedulaClienteNavigation { get; set; }
        public virtual UsuarioAdministrador CedulaNavigation { get; set; }
        public virtual Evento CodigoEventoNavigation { get; set; }
        public virtual ICollection<Acompannante> Acompannantes { get; set; }
    }
}

PerroAventurero/Controllers/ReservasController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MailKit;
using MimeKit;
using MailKit.Net.Smtp;

namespace PerroAventurero.Models
{
    public class ReservasController : Controller
    {
        private readonly PAContext _context;
        private static int code;
        private int AGE_CHILDREN = 12;

        public ReservasController(PAContext context)
        {
            _context = context;
        }

        // GET: Reservas
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Index()
        {
            var pAContext = _context.Reservas.Where(r => r.EsAceptada == null && r.ComprobantePago != null).Include(r => r.CedulaClienteNavigation).Include(r => r.CedulaNavigation).Include(r => r.CodigoEventoNavigation);
            return View(await pAContext.ToListAsync());
        }

        public async Task<IActionResult> ReservasEventos(int codigoEvento)
        {
            var pAContext = _context.Reservas.Where(r => r.CodigoEvento == codigoEvento).Include(r => r.CedulaClienteNavigation).Include(r => r.CedulaNavigation).Include(r => r.CodigoEventoNavigation);
            return View(await pAContext.ToListAsync());
        }


        public async Task<IActionResult> home()
        {
            var pAContext = _context.Reservas.Include(r => r.CedulaClienteNavigation).Include(r => r.CedulaNavigation).Include(r => r.CodigoEventoNavigation);
            return View(await pAContext.ToListAsync());
        }

        // GET: Reservas/Details/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reserva = await _context.Reservas
                .Include(r => r.CedulaClienteNavigation)
                .Include(r => r.CedulaNavigation)
                .Include(r => r.CodigoEventoNavigation)
                .FirstOrDefaultAsync(m => m.CodigoReserva == id);
            if (reserva == null)
            {
                return NotFound();
            }

            return View(reserva);
        }


        public async Task<IActionResult> Accept(int id)
        {
            var reserva = await _context.Reservas.FindAsync(id);
            Cliente cliente = await _context.Clientes.FindAsync(reserva.CedulaCliente);
            Evento evento = await _context.Eventos.FindAsync(reserva.CodigoEvento);

            MimeMessage message = new MimeMessage();
            message.From.Add(new MailboxAddress("Perro Aventurero", "perroaventurero.info@gmail.com"));
            SmtpClient client = new SmtpClient();
            string email = "perroaventurero.info@gmail.com";
            string password = "paonline08";

            message.To.Add(MailboxAddress.Parse(cliente.Correo.ToString()));
            message.Subject = "Estado de reservación a evento de Perro Aventurero";
            string body = "Se ha realizado una reservación con los siguientes datos.\n\n" +
                     "Nombre de la persona: " + cliente.NombreCompleto.ToString() + "\n" +
                     "Cédula: " + cliente.CedulaCliente.ToString() + "\n" +
                     "Nombre del evento: " + evento.NombreEvento.ToString() + "\n" +
                     "Lugar del evento: " + evento.Lugar.ToString() + "\n" +
                     "Fecha: " + evento.Fecha.ToString("D") + "\n" +
                     "Hora de entrada : " + reserva.HoraEntrada.ToString("h: mm tt") + "\n" +
                     "Grupo : " + reserva.Grupo.ToString() + "\n" +
                     "Cantidad entradas generales: " + reserva.EntradasGenerales.ToString() + "\n" +
                     "Cantidad entradas niños: " + reserva.EntradasNinnos.ToString() + "\n" +
                     "Precio total: " + Math.Truncate(reserva.PrecioTotal) + "\n" +
                     "Gracias por realizar la reservación";

            message.Body = new TextPart("plain")
            {
                Text = body,
            };

            try
            {
                client.Connect("smtp.gmail.com", 465, true);
                client.Authenticate(email, password);
                client.Send(message);
            }
            catch (Exception ex)
            {
                // TODO: handle exception
                throw new InvalidOperationException(ex.Message);
            }
            finally
            {

                client.Disconnect(true);
                client.Dispose();
            }

            reserva.EsAceptada = true;
            _context.Update(reserva);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Reject(int id)
        {
            var reserva = await _context.Reservas.FindAsync(id);
            Cliente cliente = await _context.Clientes.FindAsync(reserva.CedulaCliente);
            Evento evento = await _context.Eventos.FindAsync(reserva.CodigoEvento);

            MimeMessage message = new MimeMessage();
            message.From.Add(new MailboxAddress("Perro Aventurero", "perroaventurero.info@gmail.com"));
            SmtpClient client = new SmtpClient();
            string email = "perroaventurero.info@gmail.com";
            string password = "paonline08";

            message.To.Add(MailboxAddress.Parse(cliente.Correo.ToString()));
            message.Subject = "Estado de reservación a evento de Perro Aventurero";

            message.Body = new TextPart("plain")
            {
                Text = "Su reserva al evento: "+evento.NombreEvento.ToString() + " ha sido rechazada",
            };

            try
            {
                client.Connect("smtp.gmail.com", 465, true);
                client.Authenticate(email, password);
                client.Send(message);
            }
            catch (Exception ex)
            {
                // TODO: handle exception
                throw new InvalidOperationException(ex.Message);
            }
            finally
            {

                client.Disconnect(true);
                client.Dispose();
            }

            Acompannante acompannate;
            while (_context.Acompannantes.Where(a => a.CodigoReserva == reserva.CodigoReserva).FirstOrDefault() != null)
            {
                acompannate = _context.Acompannantes.Where(a => a.CodigoReserva == reserva.CodigoReserva).FirstOrDefault();
                _context.Acompannantes.Remove(acompannate);
                await _context.SaveChangesAsync();
            }
            _context.Reservas.Remove(reserva);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }



        // GET: Reservas/Create
        public IActionResult Create(int id)
        {
            if (id != 0) {
                code = id;
                List<String> GroupTime = groupTime(code);

                Evento evento = (Evento)_context.Eventos.Where(eventos => eventos.CodigoEvento == code).FirstOrDefault();

                ViewBag.EntradasNinnos = evento.PrecioNinno;
                ViewBag.EntradasGenerales = evento.PrecioGeneral;
                ViewBag.GroupTimeList = GroupTime;
            ViewData["Nav"] = "false";
            ViewData["CedulaCliente"] = new SelectList(_context.Clientes, "CedulaCliente", "CedulaCliente");
            ViewData["Cedula"] = new SelectList(_context.UsuarioAdministradors, "Cedula", "Cedula");
            ViewData["CodigoEvento"] = new SelectList(_context.Eventos, "CodigoEvento", "Cedula");
            return View();
            }
            return Redirect("~/Home/Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddAcompannante([Bind("Acompannantes")] Reserva acompannante)
        {
            acompannante.Acompannantes.Add(new Acompannante());
            return PartialView("Acompannantes", acompannante);

        }


        // POST: Reservas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EntradasGenerales,EntradasNinnos,ComprobantePago,CedulaClienteNavigation")] Reserva reserva, List<char> Gender, List<short> Age, IFormFile files, string groupAndTime)
        {
            Evento evento = new Evento();
            evento = (Evento)_context.Eventos.Where(eventos => eventos.CodigoEvento == code).FirstOrDefault();
            reserva.CodigoEvento = evento.CodigoEvento;

            reserva.PrecioTotal = price(evento, Age);

            List <String> GT = divide(groupAndTime);
            reserva.Grupo = short.Parse(GT[0]);
            reserva.HoraEntrada = DateTime.Parse(GT[1]);

            reserva.FechaReserva = DateTime.Now;

            reserva.CedulaCliente = reserva.CedulaClienteNavigation.CedulaCliente;

            if (reserva.EntradasNinnos == null)
            {
                reserva.EntradasNinnos = 0;
            }

            if (validateAge(Age, reserva.EntradasNinnos, reserva.EntradasGenerales) ==  false) {
                List<String> GroupTimeR = groupTime(code);

                ViewBag.EntradasNinnos = evento.PrecioNinno;
                ViewBag.EntradasGenerales = evento.PrecioGeneral;
                ViewBag.GroupTimeList = GroupTimeR;
                ModelState.AddModelError("EntradasNinnos", "Debe ingresar correctamente las edades de los acompañantes, se considerará niño o niña a toda persona desde su concepción hasta los doce años de edad cumplidos");
                return View(reserva);

PerroAventurero/Views/Reservas/Delete.cshtml
@model PerroAventurero.Models.Reserva

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Reserva</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EntradasGenerales)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EntradasGenerales)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EntradasNinnos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EntradasNinnos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaReserva)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaReserva)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Grupo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Grupo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HoraEntrada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HoraEntrada)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EsAceptada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EsAceptada)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ComprobantePago)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ComprobantePago)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrecioTotal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrecioTotal)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Asistencia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Asistencia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CedulaClienteNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CedulaClienteNavigation.CedulaCliente)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CedulaNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CedulaNavigation.Cedula)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CodigoEventoNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CodigoEventoNavigation.Cedula)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CodigoReserva" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PerroAventurero/Views/Reservas/Details.cshtml
@model PerroAventurero.Models.Reserva

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Reserva</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EntradasGenerales)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EntradasGenerales)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EntradasNinnos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EntradasNinnos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaReserva)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaReserva)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Grupo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Grupo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HoraEntrada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HoraEntrada)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EsAceptada)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EsAceptada)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ComprobantePago)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ComprobantePago)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrecioTotal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrecioTotal)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Asistencia)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Asistencia)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CedulaClienteNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CedulaClienteNavigation.CedulaCliente)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CedulaNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CedulaNavigation.Cedula)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CodigoEventoNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CodigoEventoNavigation.Cedula)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CodigoReserva">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PerroAventurero/Views/Reservas/Edit.cshtml
@model PerroAventurero.Models.Reserva

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Reserva</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CodigoReserva" />
            <div class="form-group">
                <label asp-for="CodigoEvento" class="control-label"></label>
                <select asp-for="CodigoEvento" class="form-control" asp-items="ViewBag.CodigoEvento"></select>
                <span asp-validation-for="CodigoEvento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CedulaCliente" class="control-label"></label>
                <select asp-for="CedulaCliente" class="form-control" asp-items="ViewBag.CedulaCliente"></select>
                <span asp-validation-for="CedulaCliente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cedula" class="control-label"></label>
                <select asp-for="Cedula" class="form-control" asp-items="ViewBag.Cedula"></select>
                <span asp-validation-for="Cedula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntradasGenerales" class="control-label"></label>
                <input asp-for="EntradasGenerales" class="form-control" />
                <span asp-validation-for="EntradasGenerales" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntradasNinnos" class="control-label"></label>
                <input asp-for="EntradasNinnos" class="form-control" />
                <span asp-validation-for="EntradasNinnos" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaReserva" class="control-label"></label>
                <input asp-for="FechaReserva" class="form-control" />
                <span asp-validation-for="FechaReserva" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Grupo" class="control-label"></label>
                <input asp-for="Grupo" class="form-control" />
                <span asp-validation-for="Grupo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HoraEntrada" class="control-label"></label>
                <input asp-for="HoraEntrada" class="form-control" />
                <span asp-validation-for="HoraEntrada" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EsAceptada" class="control-label"></label>
                <input asp-for="EsAceptada" class="form-control" />
                <span asp-validation-for="EsAceptada" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ComprobantePago" class="control-label"></label>
                <input asp-for="ComprobantePago" class="form-control" />
                <span asp-validation-for="ComprobantePago" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrecioTotal" class="control-label"></label>
                <input asp-for="PrecioTotal" class="form-control" />
                <span asp-validation-for="PrecioTotal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Asistencia" class="control-label"></label>
                <input asp-for="Asistencia" class="form-control" />
                <span asp-validation-for="Asistencia" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PerroAventurero/Views/Reservas/Index.cshtml
@model IEnumerable<PerroAventurero.Models.Reserva>

@section Styles{
    <link rel="stylesheet" href="~/css/indexUser.css" />
}

@{
    ViewData["Title"] = "Index";
}

<div class="header">
    <div class="w-container">
        <h1 class="main-heading">Reservaciones</h1>
        <div class="divider"></div>
        
    </div>
</div>

@*<p>
        <a asp-action="Create">Create New</a>
    </p>*@

<div id="eventos" class="section">
    <div class="container">
        <div class="row justify-content-center">
            @foreach (var item in Model)
            {

                <div class="col-3" style="padding: 10px; margin-bottom:10px;">
                    <div class="project-wrapper">
                        <a class="project-wrapper inline-block">
                            @if (item.ComprobantePago == null)
                            {
                                <img src="~/images/3.png" width="211" height="211" alt="">
                            }
                            else
                            {
                                <img src="@Url.Action("getImage", "Reservas", new { id = item.CodigoReserva })" width="200" height="300" alt="">
                            }
                            <div class="form-group">

                                <p class="paragraph">Cédula: @Html.DisplayFor(modelItem => item.CedulaCliente)<br /><br />Precio total: @Html.DisplayFor(modelItem => item.PrecioTotal)</p>
                            </div>
                        </a>
                        <div class="row">
                            <div class="col-7">
                                <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
                                
                                <a nohref asp-action="Accept" asp-route-id="@item.CodigoReserva" class="btn btn-dark" onClick="alert('Reserva aceptada')">Aceptar</a>
                            </div>
                            <div class="col-4">
                                <a nohref asp-action="Reject" asp-route-id="@item.CodigoReserva" class="btn btn-dark" onClick="alert('Reserva rechazada')">Rechazar</a>
                            </div>
                        </div>
                    </div>
                </div>

            }
        </div>

    </div>
    </div>
        

PerroAventurero/Views/Reservas/ReservasEventos.cshtml
@model IEnumerable<PerroAventurero.Models.Reserva>

@{
    ViewData["Title"] = "ReservasEventos";
}


<div class="container justify-content-center p-5">
    <h2 id="reportName">Reservaciones al evento</h2>
    <br />
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Cédula</th>
                <th scope="col">Entradas generales</th>
                <th scope="col">Entradas niños</th>
                <th scope="col">Grupo</th>
                <th scope="col">Precio total</th>
                <th scope="col">Aceptada</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.CedulaCliente)</td>
                <td>@Html.DisplayFor(modelItem => item.EntradasGenerales)</td>
                <td>@Html.DisplayFor(modelItem => item.EntradasNinnos)</td>
                <td>@Html.DisplayFor(modelItem => item.Grupo)</td>
                <td>@Html.DisplayFor(modelItem => item.PrecioTotal)</td>
                @if (item.EsAceptada == true)
                {
                    <td>Sí</td>
                }
                else
                {
                    <td>No</td>

                }

               

            </tr>
            }
        </tbody>
    </table>

</div>